### Regression Model

In [11]:
import pandas as pd
import numpy as np
from configs.system import project_dir
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [13]:
p_dir = project_dir()
dataset_path = p_dir.FEATURED_DIR/'featured_dataset.csv'

df = pd.read_csv(dataset_path,index_col=0)
df.sample(2)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay
12382,64,64,1,apartment,0,2021-10-15,06:07:38,2021-10-15,07:00:35,2021-10-15 06:07:00,2021-10-15 07:00:00,53,6.10,10,4,10,4,64933.48,Friday,17.31
28295,0,211,1,company,0,2022-07-31,06:36:55,2022-07-31,07:23:06,2022-07-31 06:36:00,2022-07-31 07:23:00,46,5.32,7,6,7,6,139686.65,Sunday,17.81

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 72826 entries, 0 to 72855
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UserID          72826 non-null  int64
 1   ChargerID       72826 non-null  int64
 2   ChargerCompany  72826 non-null  int64
 3   Location        72826 non-null  str
 4   ChargerType     72826 non-null  int64
 5   StartDay        72826 non-null  str
 6   StartTime       72826 non-null  str
 7   EndDay          72826 non-null  str
 8   EndTime         72826 non-null  str
 9   StartDatetime   72826 non-null  str
 10  EndDatetime     72826 non-null  str
 11  Duration        72826 non-null  int64
 12  Demand          72826 non-null  float64
 13  StartMonth      72826 non-null  int64
 14  StartWeek       72826 non-null  int64
 15  EndMonth        72826 non-null  int64
 16  EndWeek         72826 non-null  int64
 17  DemandPerMonth  72826 non-null  float64
 18  StartDayOfWeek  72826 non-null  str
 19  DemandPerDay    72826 non-null  float64
dtypes: float64(3), int64(9), str(8)
memory usage: 11.7 MB

In [16]:
df.sample()

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay
72817,1869,2609,0,apartment,0,2022-01-25,19:37:05,2022-01-26,01:00:28,2022-01-25 19:37:00,2022-01-26 01:00:00,323,12.64,1,1,1,2,109639.33,Tuesday,17.1

In [ ]:
categorical_columns = ['Location','StartDayOfWeek']
numerical_col = ['ChargerCompany','ChargerType','Duration','StartMonth','StartWeek','DemandPerMonth','DemandPerDay']

In [26]:
X = df[['Location','StartDayOfWeek','ChargerCompany','ChargerType','Duration','StartMonth','StartWeek','DemandPerMonth','DemandPerDay']]
y = df['Demand']

In [27]:
X

,Location,StartDayOfWeek,ChargerCompany,ChargerType,Duration,StartMonth,StartWeek,DemandPerMonth,DemandPerDay
0,hotel,Thursday,1,0,185,9,3,111771.80,17.62
1,hotel,Wednesday,1,0,90,9,2,111771.80,17.53
2,hotel,Wednesday,1,0,60,9,2,111771.80,17.53
3,hotel,Thursday,1,0,344,9,3,111771.80,17.62
4,hotel,Sunday,1,0,300,9,6,111771.80,17.81
...,...,...,...,...,...,...,...,...,...
72851,public institution,Thursday,0,0,4,1,3,109639.33,17.62
72852,sightseeing,Sunday,0,1,28,10,6,64933.48,17.81
72853,sightseeing,Sunday,0,1,40,10,6,64933.48,17.81
72854,company,Thursday,0,1,8,11,3,71741.55,17.62
72855,company,Saturday,0,1,8,10,5,64933.48,17.41

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [28]:
ln = LinearRegression()

In [54]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

categorical_columns = [
    'Location','StartDayOfWeek'
]
numerical_columns = [
    'ChargerCompany','ChargerType','Duration','StartMonth','StartWeek'
]

preprocessor = ColumnTransformer(
    transformers=[
        ('cat',OneHotEncoder(handle_unknown='ignore'),categorical_columns),
        ('num','passthrough',numerical_columns)
    ]
)


model = Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('regressor',LinearRegression())
    ]
)

In [55]:
model.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Location',
                                                   'StartDayOfWeek']),
                                                 ('num', 'passthrough',
                                                  ['ChargerCompany',
                                                   'ChargerType', 'Duration',
                                                   'StartMonth',
                                                   'StartWeek'])])),
                ('regressor', LinearRegression())])

In [56]:
y_pred = model.predict(X_test)

In [58]:
r2_score_ln = r2_score(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)

print('Linear Regression Score')
print(r2_score_ln)
print(mae)
print(mse)

Linear Regression Score
0.5676364109232173
5.623351960962902
77.91109028666288

### Decision Tree Regression

In [62]:
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [64]:

depths = [1,2,3,4,5,6,7,8,9,10]

for depth in depths:
    dt = DecisionTreeClassifier(max_depth=depth,random_state=42)

    dt.fit(X_train,y_train)

ValueError: could not convert string to float: 'hotel'