### Cleaning of Dataset

In [1]:
import pandas as pd
import numpy as np
from configs.system import project_dir

In [6]:
p_dir = project_dir()
data_dir = p_dir.RAW_DIR
clean_dir = p_dir.PROCESSED_DIR
dataset_path = data_dir/'ChargingRecords.csv'

In [8]:
## loading the dataset
df = pd.read_csv(dataset_path)
df.sample(4)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
21869,0,145,1,public area,0,2022-02-21,15:09:16,2022-02-21,16:56:24,2022-02-21 15:09,2022-02-21 16:56,107,12.93
65034,464,1348,0,market,1,2022-06-08,14:14:08,2022-06-08,14:18:28,2022-06-08 14:14,2022-06-08 14:18,4,2.37
48318,87,552,0,public institution,0,2022-05-18,5:11:33,2022-05-18,6:45:25,2022-05-18 5:11,2022-05-18 6:45,94,11.10
6903,0,29,1,resort,0,2022-05-23,7:57:00,2022-05-23,10:56:57,2022-05-23 7:57,2022-05-23 10:56,180,19.80

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72856 entries, 0 to 72855
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UserID          72856 non-null  int64
 1   ChargerID       72856 non-null  int64
 2   ChargerCompany  72856 non-null  int64
 3   Location        72856 non-null  str
 4   ChargerType     72856 non-null  int64
 5   StartDay        72856 non-null  str
 6   StartTime       72856 non-null  str
 7   EndDay          72856 non-null  str
 8   EndTime         72856 non-null  str
 9   StartDatetime   72856 non-null  str
 10  EndDatetime     72856 non-null  str
 11  Duration        72856 non-null  int64
 12  Demand          72856 non-null  float64
dtypes: float64(1), int64(5), str(7)
memory usage: 7.2 MB

In [ ]:
### fixing the date time columns
df['StartDay'] = pd.to_datetime(df['StartDay']).dt.date
df['EndDay'] = pd.to_datetime(df['EndDay']).dt.date
df['StartDatetime'] = pd.to_datetime(df['StartDatetime'])
df['EndDatetime'] = pd.to_datetime(df['EndDatetime'])

In [ ]:
df['StartTime'] = pd.to_datetime(df['StartTime']).dt.time
df['EndTime'] = pd.to_datetime(df['EndTime']).dt.time

/tmp/ipykernel_97896/3054873057.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['EndTime'] = pd.to_datetime(df['EndTime']).dt.time

In [28]:
df.sample(4)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
58850,167,971,0,public area,1,2022-03-20,15:52:24,2022-03-20,16:05:49,2022-03-20 15:52:00,2022-03-20 16:05:00,13,2.53
44262,0,431,1,camping,0,2021-10-31,05:23:58,2021-10-31,09:02:06,2021-10-31 05:23:00,2021-10-31 09:02:00,218,23.18
29870,0,230,1,public area,0,2022-04-11,19:37:27,2022-04-11,21:31:17,2022-04-11 19:37:00,2022-04-11 21:31:00,114,7.97
66580,326,1488,0,public parking lot,1,2022-01-03,15:02:00,2022-01-03,15:45:48,2022-01-03 15:02:00,2022-01-03 15:45:00,44,24.60

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72856 entries, 0 to 72855
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UserID          72856 non-null  int64
 1   ChargerID       72856 non-null  int64
 2   ChargerCompany  72856 non-null  int64
 3   Location        72856 non-null  str
 4   ChargerType     72856 non-null  int64
 5   StartDay        72856 non-null  object
 6   StartTime       72856 non-null  object
 7   EndDay          72856 non-null  object
 8   EndTime         72856 non-null  object
 9   StartDatetime   72856 non-null  datetime64[us]
 10  EndDatetime     72856 non-null  datetime64[us]
 11  Duration        72856 non-null  int64
 12  Demand          72856 non-null  float64
dtypes: datetime64[us](2), float64(1), int64(5), object(4), str(1)
memory usage: 7.2+ MB

In [30]:
df.duplicated().sum()

np.int64(13)

In [31]:
df.drop_duplicates(inplace=True)

In [32]:
df.duplicated().sum()

np.int64(0)

### Checking for outliers

In [34]:
df.describe()

,UserID,ChargerID,ChargerCompany,ChargerType,StartDatetime,EndDatetime,Duration,Demand
count,72843.000000,72843.000000,72843.000000,72843.000000,72843,72843,72843.000000,72843.000000
mean,338.084716,525.404143,0.627500,0.205195,2022-04-19 11:51:21.575717,2022-04-19 14:26:51.334788,151.183998,17.442667
min,0.000000,1.000000,0.000000,0.000000,2021-09-30 17:14:00,2021-10-01 00:07:00,-29.000000,0.010000
25%,0.000000,107.000000,0.000000,0.000000,2022-01-25 21:39:30,2022-01-26 02:36:00,40.000000,7.530000
50%,62.000000,301.000000,1.000000,0.000000,2022-04-27 14:19:00,2022-04-27 15:39:00,112.000000,14.100000
75%,407.000000,738.000000,1.000000,0.000000,2022-07-17 09:58:30,2022-07-17 11:47:00,202.000000,23.200000
max,2501.000000,2671.000000,1.000000,1.000000,2022-09-30 23:11:00,2022-09-30 23:52:00,1573.000000,97.000000
std,553.916404,569.481406,0.483474,0.403847,NaN,NaN,146.420312,13.491446

In [36]:
df.loc[df['Duration']==-29.0]

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
55422,1403,775,0,market,1,2022-02-15,15:04:54,2022-02-15,14:35:36,2022-02-15 15:04:00,2022-02-15 14:35:00,-29,11.68

In [37]:
df.shape

(72843, 13)

In [42]:
df = df.drop(df[df['Duration']== -29.0].index)

In [43]:
df.shape

(72842, 13)

In [44]:
df[df['Duration'] < 0]

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
55425,1403,775,0,market,1,2022-02-24,14:27:44,2022-02-24,14:18:35,2022-02-24 14:27:00,2022-02-24 14:18:00,-9,34.56
55427,1403,775,0,market,1,2022-01-17,14:47:03,2022-01-17,14:39:24,2022-01-17 14:47:00,2022-01-17 14:39:00,-8,17.77
55455,37,778,0,market,1,2022-04-29,18:58:46,2022-04-29,18:52:20,2022-04-29 18:58:00,2022-04-29 18:52:00,-6,31.90
55457,55,778,0,market,1,2022-05-07,16:24:20,2022-05-07,16:03:03,2022-05-07 16:24:00,2022-05-07 16:03:00,-21,13.39
55458,74,778,0,market,1,2022-04-29,15:48:51,2022-04-29,15:43:07,2022-04-29 15:48:00,2022-04-29 15:43:00,-6,19.36
55459,92,778,0,market,1,2022-03-27,15:17:53,2022-03-27,15:10:38,2022-03-27 15:17:00,2022-03-27 15:10:00,-7,20.99
55460,92,778,0,market,1,2022-02-05,18:52:39,2022-02-05,18:50:15,2022-02-05 18:52:00,2022-02-05 18:50:00,-2,31.59
55464,266,778,0,market,1,2022-05-08,12:02:28,2022-05-08,11:42:02,2022-05-08 12:02:00,2022-05-08 11:42:00,-20,3.28
55465,326,778,0,market,1,2022-01-09,14:29:15,2022-01-09,14:20:28,2022-01-09 14:29:00,2022-01-09 14:20:00,-9,31.68
55469,1768,778,0,market,1,2022-04-07,12:25:32,2022-04-07,12:12:11,2022-04-07 12:25:00,2022-04-07 12:12:00,-13,53.24
57800,55,922,0,market,1,2022-04-09,11:29:43,2022-04-09,11:23:46,2022-04-09 11:29:00,2022-04-09 11:23:00,-6,41.08
57802,1474,922,0,market,1,2022-05-05,17:48:01,2022-05-05,17:31:39,2022-05-05 17:48:00,2022-05-05 17:31:00,-16,51.99
57803,1766,922,0,market,1,2022-04-17,18:59:44,2022-04-17,18:54:21,2022-04-17 18:59:00,2022-04-17 18:54:00,-5,15.04
63503,1575,1229,0,market,1,2022-03-19,15:32:26,2022-03-19,15:24:33,2022-03-19 15:32:00,2022-03-19 15:24:00,-8,37.97
63504,1575,1229,0,market,1,2022-03-22,17:19:11,2022-03-22,16:55:39,2022-03-22 17:19:00,2022-03-22 16:55:00,-24,25.49
65029,140,1347,0,market,1,2022-03-30,13:20:34,2022-03-30,13:04:57,2022-03-30 13:20:00,2022-03-30 13:04:00,-16,23.10

In [45]:
df = df.drop(df[df['Duration']<0].index)

In [46]:
df.shape

(72826, 13)

In [48]:
df.describe()

,UserID,ChargerID,ChargerCompany,ChargerType,StartDatetime,EndDatetime,Duration,Demand
count,72826.000000,72826.000000,72826.000000,72826.000000,72826,72826,72826.000000,72826.000000
mean,337.978208,525.319172,0.627647,0.205009,2022-04-19 11:59:54.617581,2022-04-19 14:35:26.723422,151.222105,17.440366
min,0.000000,1.000000,0.000000,0.000000,2021-09-30 17:14:00,2021-10-01 00:07:00,0.000000,0.010000
25%,0.000000,107.000000,0.000000,0.000000,2022-01-25 21:36:30,2022-01-26 02:06:00,40.000000,7.530000
50%,61.000000,300.000000,1.000000,0.000000,2022-04-27 14:29:00,2022-04-27 15:43:30,112.000000,14.100000
75%,407.000000,738.000000,1.000000,0.000000,2022-07-17 10:18:45,2022-07-17 11:53:30,202.000000,23.200000
max,2501.000000,2671.000000,1.000000,1.000000,2022-09-30 23:11:00,2022-09-30 23:52:00,1573.000000,97.000000
std,553.828304,569.513697,0.483435,0.403711,NaN,NaN,146.416111,13.490614

In [49]:
df[df['Duration'] > 1000]

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
1495,0,8,1,hotel,0,2022-02-08,19:20:42,2022-02-09,17:40:56,2022-02-08 19:20:00,2022-02-09 17:40:00,1324,0.04
1505,0,8,1,hotel,0,2022-01-19,20:55:35,2022-01-20,15:53:41,2022-01-19 20:55:00,2022-01-20 15:53:00,1123,0.01
1517,0,8,1,hotel,0,2022-05-12,19:41:56,2022-05-13,18:30:30,2022-05-12 19:41:00,2022-05-13 18:30:00,1369,52.64
2451,245,13,1,apartment,0,2022-04-23,15:29:24,2022-04-23,18:33:44,2022-04-23 15:29:00,2022-04-23 18:33:00,1034,20.90
2955,0,16,1,apartment,0,2022-06-19,18:31:59,2022-06-20,13:43:43,2022-06-19 18:31:00,2022-06-20 13:43:00,1152,4.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
71796,782,2303,0,apartment,0,2022-02-21,18:37:06,2022-02-22,11:44:10,2022-02-21 18:37:00,2022-02-22 11:44:00,1027,20.02
71798,782,2304,0,apartment,0,2022-08-06,23:03:59,2022-08-07,16:04:36,2022-08-06 23:03:00,2022-08-07 16:04:00,1021,8.61
72296,1126,2431,0,apartment,0,2021-12-22,13:15:08,2021-12-24,09:00:01,2021-12-22 13:15:00,2021-12-24 09:00:00,1185,4.75
72363,1295,2478,0,hotel,0,2021-12-24,20:47:15,2021-12-25,16:07:12,2021-12-24 20:47:00,2021-12-25 16:07:00,1160,45.99
72471,1859,2504,0,market,0,2021-12-03,15:55:07,2021-12-04,10:32:10,2021-12-03 15:55:00,2021-12-04 10:32:00,1117,37.60

In [51]:
df.to_csv(clean_dir/'cleaned_dataset.csv')