## Overview of the Dataset

In [1]:
import pandas as pd
from configs.system import project_dir

In [9]:
p_dir = project_dir()
data_dir = p_dir.RAW_DIR

dataset_dir = data_dir/'ChargingRecords.csv'
df = pd.read_csv(dataset_dir)
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
5001,280,21,1,apartment,0,2022-08-22,7:05:46,2022-08-22,10:54:27,2022-08-22 7:05,2022-08-22 10:54,229,26.2
1037,0,5,1,apartment,0,2022-04-20,0:08:26,2022-04-20,4:21:15,2022-04-20 0:08,2022-04-20 4:21,251,30.3
25419,927,176,1,public area,0,2022-03-22,23:07:36,2022-03-23,7:54:47,2022-03-22 23:07,2022-03-23 7:54,527,52.7

In [10]:
df.shape

(72856, 13)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 72856 entries, 0 to 72855
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   UserID          72856 non-null  int64
 1   ChargerID       72856 non-null  int64
 2   ChargerCompany  72856 non-null  int64
 3   Location        72856 non-null  str
 4   ChargerType     72856 non-null  int64
 5   StartDay        72856 non-null  str
 6   StartTime       72856 non-null  str
 7   EndDay          72856 non-null  str
 8   EndTime         72856 non-null  str
 9   StartDatetime   72856 non-null  str
 10  EndDatetime     72856 non-null  str
 11  Duration        72856 non-null  int64
 12  Demand          72856 non-null  float64
dtypes: float64(1), int64(5), str(7)
memory usage: 7.2 MB

In [13]:
df.duplicated().sum()

np.int64(13)

In [14]:
df.describe()

,UserID,ChargerID,ChargerCompany,ChargerType,Duration,Demand
count,72856.000000,72856.000000,72856.000000,72856.00000,72856.000000,72856.000000
mean,338.164667,525.489212,0.627443,0.20524,151.194054,17.444445
std,553.970996,569.544469,0.483489,0.40388,146.430286,13.492728
min,0.000000,1.000000,0.000000,0.00000,-29.000000,0.010000
25%,0.000000,107.000000,0.000000,0.00000,40.000000,7.530000
50%,62.000000,301.000000,1.000000,0.00000,112.000000,14.100000
75%,407.000000,738.000000,1.000000,0.00000,202.000000,23.200000
max,2501.000000,2671.000000,1.000000,1.00000,1573.000000,97.000000

In [15]:
df['ChargerCompany'].value_counts()

ChargerCompany
1    45713
0    27143
Name: count, dtype: int64

In [16]:
df['Location'].value_counts()

Location
public area           14082
apartment             14038
resort                 8854
hotel                  8600
company                7558
public institution     7023
public parking lot     3396
market                 3005
restaurant             2222
camping                1630
sightseeing            1203
golf                   1029
accommodation           187
bus garage               29
Name: count, dtype: int64

In [18]:
df['ChargerType'].value_counts()

ChargerType
0    57903
1    14953
Name: count, dtype: int64

In [19]:
df.columns

Index(['UserID', 'ChargerID', 'ChargerCompany', 'Location', 'ChargerType',
       'StartDay', 'StartTime', 'EndDay', 'EndTime', 'StartDatetime',
       'EndDatetime', 'Duration', 'Demand'],
      dtype='str')

In [29]:
df['UserID'].duplicated(keep=False).sum()

np.int64(72193)

In [30]:
df['ChargerID'].duplicated(keep=False).sum()

np.int64(72606)

In [31]:
df.loc[df['UserID'].duplicated(),'UserID']

1           0
2           0
3           0
4           0
5           0
         ...
72850    2128
72852    2379
72853    2388
72854    2388
72855    2388
Name: UserID, Length: 70519, dtype: int64

In [33]:
df[df[["UserID",'ChargerID']].duplicated(keep=False)]

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
0,0,1,1,hotel,0,2022-09-15,20:54:02,2022-09-15,23:59:13,2022-09-15 20:54,2022-09-15 23:59,185,20.36
1,0,1,1,hotel,0,2022-09-14,20:01:05,2022-09-14,21:31:04,2022-09-14 20:01,2022-09-14 21:31,90,10.19
2,0,1,1,hotel,0,2022-09-14,18:54:30,2022-09-14,19:54:29,2022-09-14 18:54,2022-09-14 19:54,60,6.78
3,0,1,1,hotel,0,2022-09-29,18:32:51,2022-09-30,0:16:42,2022-09-29 18:32,2022-09-30 0:16,344,37.65
4,0,1,1,hotel,0,2022-09-25,19:30:15,2022-09-26,0:30:14,2022-09-25 19:30,2022-09-26 0:30,300,33.81
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72838,2173,2609,0,apartment,0,2021-12-28,11:54:39,2021-12-28,17:07:34,2021-12-28 11:54,2021-12-28 17:07,313,12.09
72849,2128,2647,0,apartment,0,2022-01-04,21:07:44,2022-01-04,22:49:37,2022-01-04 21:07,2022-01-04 22:49,102,11.38
72850,2128,2647,0,apartment,0,2022-01-30,14:40:11,2022-01-30,20:12:02,2022-01-30 14:40,2022-01-30 20:12,332,10.90
72854,2388,2671,0,company,1,2021-11-18,11:37:44,2021-11-18,11:45:37,2021-11-18 11:37,2021-11-18 11:45,8,3.80
72855,2388,2671,0,company,1,2021-10-30,17:29:02,2021-10-30,17:36:47,2021-10-30 17:29,2021-10-30 17:36,8,3.67

In [37]:
location_mean = df.groupby('Location')['Demand'].mean().to_frame()
location_mean

                       Demand
Location
accommodation       29.055829
apartment           18.746507
bus garage          28.587586
camping             25.525288
company             16.247879
golf                16.718299
hotel               14.704900
market              16.567338
public area         17.906683
public institution  17.399318
public parking lot  17.186767
resort              17.280838
restaurant          17.813123
sightseeing         15.245129

In [38]:
df.columns

Index(['UserID', 'ChargerID', 'ChargerCompany', 'Location', 'ChargerType',
       'StartDay', 'StartTime', 'EndDay', 'EndTime', 'StartDatetime',
       'EndDatetime', 'Duration', 'Demand'],
      dtype='str')

In [49]:
df[['StartDay','EndDay']].agg(['min','max'])

       StartDay      EndDay
min  2021-09-30  2021-10-01
max  2022-09-30  2022-09-30

In [41]:
df['StartDay'].min()

'2021-09-30'

In [44]:
df['EndDay'].max()

'2022-09-30'

In [50]:
df.sample(4)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
67048,1008,1521,0,sightseeing,1,2022-08-22,9:16:32,2022-08-22,9:42:26,2022-08-22 9:16,2022-08-22 9:42,26,18.81
50594,209,589,0,sightseeing,0,2022-09-11,14:48:27,2022-09-11,16:09:17,2022-09-11 14:48,2022-09-11 16:09,81,9.37
60739,0,1073,1,resort,0,2022-09-17,8:57:33,2022-09-17,10:09:58,2022-09-17 8:57,2022-09-17 10:09,72,8.01
25183,0,174,1,hotel,0,2022-07-28,15:41:31,2022-07-28,20:22:46,2022-07-28 15:41,2022-07-28 20:22,281,32.24

In [53]:
df.groupby('ChargerType')['Demand'].mean()

ChargerType
0    17.054121
1    18.955911
Name: Demand, dtype: float64

In [54]:
df['ChargerType'].value_counts(0)

ChargerType
0    57903
1    14953
Name: count, dtype: int64

In [55]:
df['ChargerCompany'].value_counts()

ChargerCompany
1    45713
0    27143
Name: count, dtype: int64

In [56]:
df.groupby('ChargerCompany')['Demand'].mean()

ChargerCompany
0    16.696717
1    17.888424
Name: Demand, dtype: float64

In [57]:
df.groupby('ChargerCompany')['Duration'].agg(['mean','count'])

                      mean  count
ChargerCompany
0               104.271525  27143
1               179.055236  45713

In [58]:
df.groupby('ChargerType')['Duration'].agg(['mean','count'])

                   mean  count
ChargerType
0            180.943146  57903
1             35.995653  14953