### Feature Engineering

In [41]:
import pandas as pd
import numpy as np
from configs.system import project_dir

In [42]:
p_dir = project_dir()
clean_dir = p_dir.PROCESSED_DIR
dataset_path = clean_dir/'cleaned_dataset.csv'

In [43]:
df = pd.read_csv(dataset_path,index_col=0)
df.sample(4)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
50324,1230,580,1,apartment,0,2022-06-07,17:52:08,2022-06-07,19:46:58,2022-06-07 17:52:00,2022-06-07 19:46:00,115,12.88
32532,79,262,1,restaurant,0,2022-06-15,06:46:01,2022-06-15,09:02:12,2022-06-15 06:46:00,2022-06-15 09:02:00,136,14.23
18047,0,105,1,hotel,0,2022-04-14,19:57:39,2022-04-14,22:47:42,2022-04-14 19:57:00,2022-04-14 22:47:00,169,18.18
61083,539,1089,0,public institution,1,2022-09-30,17:33:45,2022-09-30,17:46:51,2022-09-30 17:33:00,2022-09-30 17:46:00,13,1.13

In [44]:
df['StartMonth'] = pd.to_datetime(df['StartDay']).dt.month
df['StartWeek'] = pd.to_datetime(df['StartDay']).dt.dayofweek

df['EndMonth'] = pd.to_datetime(df['EndDay']).dt.month
df['EndWeek'] = pd.to_datetime(df['EndDay']).dt.dayofweek

In [45]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek
42576,396,384,0,public area,1,2022-04-19,13:47:17,2022-04-19,13:55:15,2022-04-19 13:47:00,2022-04-19 13:55:00,8,5.39,4,1,4,1
69655,1766,1859,0,resort,1,2022-04-17,09:30:41,2022-04-17,09:47:43,2022-04-17 09:30:00,2022-04-17 09:47:00,17,2.96,4,6,4,6
6306,0,25,1,hotel,0,2022-01-05,18:33:31,2022-01-05,21:07:24,2022-01-05 18:33:00,2022-01-05 21:07:00,154,17.08,1,2,1,2

In [46]:
df['DemandPerMonth'] = df.groupby('StartMonth')['Demand'].transform('sum')

In [47]:
df.sample(2)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth
5880,0,25,1,hotel,0,2022-06-11,18:55:11,2022-06-11,18:55:30,2022-06-11 18:55:00,2022-06-11 18:55:00,0,0.02,6,5,6,5,117564.42
14808,0,81,1,company,0,2021-10-12,09:34:33,2021-10-12,11:07:34,2021-10-12 09:34:00,2021-10-12 11:07:00,93,11.00,10,1,10,1,64933.48

In [48]:
df.groupby('StartMonth')['DemandPerMonth'].count()

StartMonth
1     6305
2     5837
3     5944
4     6001
5     6688
6     6729
7     7888
8     8083
9     6282
10    3930
11    4281
12    4858
Name: DemandPerMonth, dtype: int64

In [49]:
df.groupby('StartMonth')['DemandPerMonth'].sum().sort_values(ascending=False)

StartMonth
8     1.156203e+09
7     1.101848e+09
6     7.910910e+08
5     7.710183e+08
9     7.021504e+08
1     6.912760e+08
4     6.256263e+08
3     6.175581e+08
2     6.020396e+08
12    4.136980e+08
11    3.071256e+08
10    2.551886e+08
Name: DemandPerMonth, dtype: float64

In [50]:
df.groupby('StartMonth')['Demand'].sum().sort_values(ascending=False)

StartMonth
8     143041.27
7     139686.65
6     117564.42
5     115283.83
9     111771.80
1     109639.33
4     104253.67
3     103896.05
2     103141.96
12     85158.09
11     71741.55
10     64933.48
Name: Demand, dtype: float64

In [51]:
df.columns

Index(['UserID', 'ChargerID', 'ChargerCompany', 'Location', 'ChargerType',
       'StartDay', 'StartTime', 'EndDay', 'EndTime', 'StartDatetime',
       'EndDatetime', 'Duration', 'Demand', 'StartMonth', 'StartWeek',
       'EndMonth', 'EndWeek', 'DemandPerMonth'],
      dtype='str')

In [52]:
df['StartDayOfWeek'] = pd.to_datetime(df['StartDay']).dt.day_name()

In [53]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek
2178,0,13,1,apartment,0,2022-01-26,17:06:56,2022-01-26,18:49:22,2022-01-26 17:06:00,2022-01-26 18:49:00,102,11.79,1,2,1,2,109639.33,Wednesday
56279,512,833,0,market,1,2022-09-01,15:40:15,2022-09-01,15:56:03,2022-09-01 15:40:00,2022-09-01 15:56:00,16,12.21,9,3,9,3,111771.80,Thursday
63726,268,1241,0,public institution,1,2022-01-07,12:56:40,2022-01-07,13:36:41,2022-01-07 12:56:00,2022-01-07 13:36:00,40,27.61,1,4,1,4,109639.33,Friday

In [60]:
df['DemandPerDay'] = df.groupby('StartDayOfWeek')['Demand'].transform('mean').round(2)

In [61]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay
69417,304,1818,0,public institution,0,2022-05-13,00:22:08,2022-05-13,03:12:48,2022-05-13 00:22:00,2022-05-13 03:12:00,171,10.00,5,4,5,4,115283.83,Friday,17.31
14436,36,80,1,public area,0,2022-08-29,12:57:18,2022-08-29,14:01:36,2022-08-29 12:57:00,2022-08-29 14:01:00,64,7.49,8,0,8,0,143041.27,Monday,17.35
20243,0,125,1,hotel,0,2021-10-20,19:31:48,2021-10-20,22:09:29,2021-10-20 19:31:00,2021-10-20 22:09:00,156,18.19,10,2,10,2,64933.48,Wednesday,17.53

In [62]:
df.groupby('StartDayOfWeek')['DemandPerDay'].mean()

StartDayOfWeek
Friday       17.31
Monday       17.35
Saturday     17.41
Sunday       17.81
Thursday     17.62
Tuesday      17.10
Wednesday    17.53
Name: DemandPerDay, dtype: float64

In [65]:
df.groupby('StartDayOfWeek')['DemandPerDay'].sum().round(2).sort_values(ascending=False)

StartDayOfWeek
Thursday     194701.00
Wednesday    190691.34
Friday       190548.48
Tuesday      182012.40
Monday       179069.35
Saturday     173037.99
Sunday       160040.66
Name: DemandPerDay, dtype: float64

In [66]:
df.shape

(72826, 20)

In [67]:
df.sample(2)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay
31636,240,250,1,public area,0,2022-02-05,20:06:30,2022-02-06,04:25:39,2022-02-05 20:06:00,2022-02-06 04:25:00,499,55.40,2,5,2,6,103141.96,Saturday,17.41
28817,317,214,1,public area,0,2022-03-27,21:19:07,2022-03-28,03:41:53,2022-03-27 21:19:00,2022-03-28 03:41:00,383,42.59,3,6,3,0,103896.05,Sunday,17.81

In [69]:
df_ = pd.read_csv(dataset_path)
df_.shape

(72826, 14)

In [70]:
print(f'before feature engineering, shape of the dataset is {df_.shape}')

print(f'after appling feature engineering, shape of the dataset i s{df.shape}')

before feature engineering, shape of the dataset is (72826, 14)
after appling feature engineering, shape of the dataset i s(72826, 20)

In [71]:
feature_dir = p_dir.FEATURED_DIR

In [72]:
df.to_csv(feature_dir/'featured_dataset.csv')

In [73]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay
48046,1123,542,0,resort,0,2022-07-09,18:27:13,2022-07-09,20:20:47,2022-07-09 18:27:00,2022-07-09 20:20:00,114,12.45,7,5,7,5,139686.65,Saturday,17.41
21644,0,140,1,apartment,0,2022-07-18,14:14:21,2022-07-18,18:23:05,2022-07-18 14:14:00,2022-07-18 18:23:00,249,27.79,7,0,7,0,139686.65,Monday,17.35
19774,0,123,1,apartment,0,2021-11-13,13:49:17,2021-11-13,14:31:20,2021-11-13 13:49:00,2021-11-13 14:31:00,42,5.00,11,5,11,5,71741.55,Saturday,17.41