### Feature Engineering

In [1]:
import pandas as pd
import numpy as np
from configs.system import project_dir

In [2]:
p_dir = project_dir()
clean_dir = p_dir.PROCESSED_DIR
dataset_path = clean_dir/'cleaned_dataset.csv'

In [3]:
df = pd.read_csv(dataset_path,index_col=0)
df.sample(4)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
16396,0,95,1,hotel,0,2022-09-24,19:58:17,2022-09-24,21:27:47,2022-09-24 19:58:00,2022-09-24 21:27:00,90,9.62
39934,0,360,1,apartment,0,2022-09-27,20:57:08,2022-09-28,01:42:26,2022-09-27 20:57:00,2022-09-28 01:42:00,285,33.25
23144,0,159,1,public area,0,2021-12-07,08:13:16,2021-12-07,08:58:03,2021-12-07 08:13:00,2021-12-07 08:58:00,45,5.10
25547,95,177,1,apartment,0,2022-05-12,23:26:59,2022-05-13,05:31:36,2022-05-12 23:26:00,2022-05-13 05:31:00,365,43.80

In [4]:
df['StartMonth'] = pd.to_datetime(df['StartDay']).dt.month
df['StartWeek'] = pd.to_datetime(df['StartDay']).dt.dayofweek

df['EndMonth'] = pd.to_datetime(df['EndDay']).dt.month
df['EndWeek'] = pd.to_datetime(df['EndDay']).dt.dayofweek

In [5]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek
1522,0,8,1,hotel,0,2022-07-03,22:15:07,2022-07-04,07:17:57,2022-07-03 22:15:00,2022-07-04 07:17:00,543,21.32,7,6,7,0
7631,0,30,1,resort,0,2022-02-25,20:45:43,2022-02-26,02:24:25,2022-02-25 20:45:00,2022-02-26 02:24:00,339,35.32,2,4,2,5
28733,0,214,1,public area,0,2022-03-28,20:09:50,2022-03-29,04:38:18,2022-03-28 20:09:00,2022-03-29 04:38:00,508,57.73,3,0,3,1

In [6]:
df['DemandPerMonth'] = df.groupby('StartMonth')['Demand'].transform('sum')

In [7]:
df.sample(2)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth
31762,1,251,1,market,0,2022-07-07,00:05:53,2022-07-07,05:30:36,2022-07-07 00:05:00,2022-07-07 05:30:00,325,35.15,7,3,7,3,139686.65
70712,1505,2046,0,public area,0,2022-03-12,09:55:47,2022-03-12,12:11:54,2022-03-12 09:55:00,2022-03-12 12:11:00,136,14.80,3,5,3,5,103896.05

In [8]:
df.groupby('StartMonth')['DemandPerMonth'].count()

StartMonth
1     6305
2     5837
3     5944
4     6001
5     6688
6     6729
7     7888
8     8083
9     6282
10    3930
11    4281
12    4858
Name: DemandPerMonth, dtype: int64

In [9]:
df.groupby('StartMonth')['DemandPerMonth'].sum().sort_values(ascending=False)

StartMonth
8     1.156203e+09
7     1.101848e+09
6     7.910910e+08
5     7.710183e+08
9     7.021504e+08
1     6.912760e+08
4     6.256263e+08
3     6.175581e+08
2     6.020396e+08
12    4.136980e+08
11    3.071256e+08
10    2.551886e+08
Name: DemandPerMonth, dtype: float64

In [10]:
df.groupby('StartMonth')['Demand'].sum().sort_values(ascending=False)

StartMonth
8     143041.27
7     139686.65
6     117564.42
5     115283.83
9     111771.80
1     109639.33
4     104253.67
3     103896.05
2     103141.96
12     85158.09
11     71741.55
10     64933.48
Name: Demand, dtype: float64

In [11]:
df.columns

Index(['UserID', 'ChargerID', 'ChargerCompany', 'Location', 'ChargerType',
       'StartDay', 'StartTime', 'EndDay', 'EndTime', 'StartDatetime',
       'EndDatetime', 'Duration', 'Demand', 'StartMonth', 'StartWeek',
       'EndMonth', 'EndWeek', 'DemandPerMonth'],
      dtype='str')

In [12]:
df['StartDayOfWeek'] = pd.to_datetime(df['StartDay']).dt.day_name()

In [13]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek
15253,0,84,1,public area,0,2021-11-01,12:22:36,2021-11-01,16:35:20,2021-11-01 12:22:00,2021-11-01 16:35:00,250,28.88,11,0,11,0,71741.55,Monday
58108,137,945,1,public institution,0,2022-09-30,14:07:43,2022-09-30,17:27:25,2022-09-30 14:07:00,2022-09-30 17:27:00,200,20.00,9,4,9,4,111771.80,Friday
16762,1534,95,1,hotel,0,2022-05-08,18:10:53,2022-05-08,19:10:52,2022-05-08 18:10:00,2022-05-08 19:10:00,60,6.51,5,6,5,6,115283.83,Sunday

In [14]:
df['DemandPerDay'] = df.groupby('StartDayOfWeek')['Demand'].transform('mean').round(2)

In [15]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay
32254,422,260,1,public institution,0,2022-05-13,20:14:20,2022-05-14,03:42:39,2022-05-13 20:14:00,2022-05-14 03:42:00,448,48.47,5,4,5,5,115283.83,Friday,17.31
34679,0,281,1,restaurant,0,2021-11-20,17:08:02,2021-11-20,18:45:45,2021-11-20 17:08:00,2021-11-20 18:45:00,98,11.16,11,5,11,5,71741.55,Saturday,17.41
12555,291,64,1,apartment,0,2022-01-20,14:35:50,2022-01-20,20:57:17,2022-01-20 14:35:00,2022-01-20 20:57:00,381,46.00,1,3,1,3,109639.33,Thursday,17.62

In [16]:
df.groupby('StartDayOfWeek')['DemandPerDay'].mean()

StartDayOfWeek
Friday       17.31
Monday       17.35
Saturday     17.41
Sunday       17.81
Thursday     17.62
Tuesday      17.10
Wednesday    17.53
Name: DemandPerDay, dtype: float64

In [17]:
df.groupby('StartDayOfWeek')['DemandPerDay'].sum().round(2).sort_values(ascending=False)

StartDayOfWeek
Thursday     194701.00
Wednesday    190691.34
Friday       190548.48
Tuesday      182012.40
Monday       179069.35
Saturday     173037.99
Sunday       160040.66
Name: DemandPerDay, dtype: float64

In [18]:
df.shape

(72826, 20)

In [19]:
df.sample(2)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay
22217,0,150,1,resort,0,2022-07-23,06:22:48,2022-07-23,08:09:08,2022-07-23 06:22:00,2022-07-23 08:09:00,105,12.12,7,5,7,5,139686.65,Saturday,17.41
45175,1956,445,0,public area,1,2022-02-11,18:47:18,2022-02-11,19:01:32,2022-02-11 18:47:00,2022-02-11 19:01:00,14,9.76,2,4,2,4,103141.96,Friday,17.31

In [20]:
df_ = pd.read_csv(dataset_path)
df_.shape

(72826, 14)

In [21]:
print(f'before feature engineering, shape of the dataset is {df_.shape}')

print(f'after appling feature engineering, shape of the dataset i s{df.shape}')

before feature engineering, shape of the dataset is (72826, 14)
after appling feature engineering, shape of the dataset i s(72826, 20)

In [22]:
feature_dir = p_dir.FEATURED_DIR

In [23]:
from datetime import time

df['StartTime'] = pd.to_datetime(df['StartTime'],format='%H:%M:%S').dt.time

df['Shift'] = df['StartTime'].apply(
    lambda x: 'Day' if x < time(14,0) else 'Night'
)

In [24]:
df.groupby('Shift')['Demand'].mean().round(2)

Shift
Day      15.50
Night    18.67
Name: Demand, dtype: float64

In [25]:
df.groupby('Shift')['Demand'].count()

Shift
Day      28259
Night    44567
Name: Demand, dtype: int64

In [ ]:
df.to_csv(feature_dir/'featured_dataset.csv')

In [27]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,...,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay,Shift
1864,0,9,1,hotel,0,2021-11-23,12:53:04,2021-11-23,16:17:53,2021-11-23 12:53:00,...,205,22.30,11,1,11,1,71741.55,Tuesday,17.10,Day
40770,0,372,1,apartment,0,2022-09-23,14:49:25,2022-09-23,20:55:31,2022-09-23 14:49:00,...,366,42.38,9,4,9,4,111771.80,Friday,17.31,Night
63367,113,1223,0,apartment,0,2022-07-12,18:55:20,2022-07-12,22:53:50,2022-07-12 18:55:00,...,239,22.94,7,1,7,1,139686.65,Tuesday,17.10,Night

In [ ]:
df['only-time']

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,...,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay,Shift
0,0,1,1,hotel,0,2022-09-15,20:54:02,2022-09-15,23:59:13,2022-09-15 20:54:00,...,185,20.36,9,3,9,3,111771.80,Thursday,17.62,Night
1,0,1,1,hotel,0,2022-09-14,20:01:05,2022-09-14,21:31:04,2022-09-14 20:01:00,...,90,10.19,9,2,9,2,111771.80,Wednesday,17.53,Night
2,0,1,1,hotel,0,2022-09-14,18:54:30,2022-09-14,19:54:29,2022-09-14 18:54:00,...,60,6.78,9,2,9,2,111771.80,Wednesday,17.53,Night
3,0,1,1,hotel,0,2022-09-29,18:32:51,2022-09-30,00:16:42,2022-09-29 18:32:00,...,344,37.65,9,3,9,4,111771.80,Thursday,17.62,Night
4,0,1,1,hotel,0,2022-09-25,19:30:15,2022-09-26,00:30:14,2022-09-25 19:30:00,...,300,33.81,9,6,9,0,111771.80,Sunday,17.81,Night
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72851,2155,2649,0,public institution,0,2022-01-27,09:54:44,2022-01-27,09:58:57,2022-01-27 09:54:00,...,4,0.50,1,3,1,3,109639.33,Thursday,17.62,Day
72852,2379,2670,0,sightseeing,1,2021-10-31,14:52:11,2021-10-31,15:20:28,2021-10-31 14:52:00,...,28,16.53,10,6,10,6,64933.48,Sunday,17.81,Night
72853,2388,2670,0,sightseeing,1,2021-10-03,13:52:14,2021-10-03,14:32:13,2021-10-03 13:52:00,...,40,12.20,10,6,10,6,64933.48,Sunday,17.81,Day
72854,2388,2671,0,company,1,2021-11-18,11:37:44,2021-11-18,11:45:37,2021-11-18 11:37:00,...,8,3.80,11,3,11,3,71741.55,Thursday,17.62,Day
72855,2388,2671,0,company,1,2021-10-30,17:29:02,2021-10-30,17:36:47,2021-10-30 17:29:00,...,8,3.67,10,5,10,5,64933.48,Saturday,17.41,Night