### Feature Engineering

In [1]:
import pandas as pd
import numpy as np
from configs.system import project_dir

In [2]:
p_dir = project_dir()
clean_dir = p_dir.PROCESSED_DIR
dataset_path = clean_dir/'cleaned_dataset.csv'

In [3]:
df = pd.read_csv(dataset_path,index_col=0)
df.sample(4)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand
44035,0,430,1,camping,0,2022-02-28,14:58:27,2022-02-28,17:57:15,2022-02-28 14:58:00,2022-02-28 17:57:00,179,16.33
22129,0,149,1,resort,0,2022-08-02,09:09:40,2022-08-02,10:18:54,2022-08-02 09:09:00,2022-08-02 10:18:00,69,7.72
25308,0,175,1,public area,0,2022-09-01,23:17:54,2022-09-02,02:17:54,2022-09-01 23:17:00,2022-09-02 02:17:00,180,20.59
62966,107,1200,0,apartment,0,2022-05-28,12:35:53,2022-05-28,16:29:44,2022-05-28 12:35:00,2022-05-28 16:29:00,234,3.97

In [4]:
df['StartMonth'] = pd.to_datetime(df['StartDay']).dt.month
df['StartWeek'] = pd.to_datetime(df['StartDay']).dt.dayofweek

df['EndMonth'] = pd.to_datetime(df['EndDay']).dt.month
df['EndWeek'] = pd.to_datetime(df['EndDay']).dt.dayofweek

In [5]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek
64833,135,1326,0,public institution,0,2022-02-08,18:50:44,2022-02-09,02:41:35,2022-02-08 18:50:00,2022-02-09 02:41:00,471,53.00,2,1,2,2
53294,1768,683,0,sightseeing,1,2022-03-29,14:03:28,2022-03-29,14:30:45,2022-03-29 14:03:00,2022-03-29 14:30:00,27,31.36,3,1,3,1
43141,62,401,0,public parking lot,1,2022-03-06,14:06:01,2022-03-06,14:29:49,2022-03-06 14:06:00,2022-03-06 14:29:00,24,8.86,3,6,3,6

In [6]:
df['DemandPerMonth'] = df.groupby('StartMonth')['Demand'].transform('sum')

In [7]:
df.sample(2)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth
5866,0,25,1,hotel,0,2022-07-22,14:52:22,2022-07-22,16:58:37,2022-07-22 14:52:00,2022-07-22 16:58:00,126,14.07,7,4,7,4,139686.65
48217,18,551,0,public institution,0,2022-05-24,19:57:41,2022-05-24,23:17:36,2022-05-24 19:57:00,2022-05-24 23:17:00,200,23.00,5,1,5,1,115283.83

In [8]:
df.groupby('StartMonth')['DemandPerMonth'].count()

StartMonth
1     6305
2     5837
3     5944
4     6001
5     6688
6     6729
7     7888
8     8083
9     6282
10    3930
11    4281
12    4858
Name: DemandPerMonth, dtype: int64

In [9]:
df.groupby('StartMonth')['DemandPerMonth'].sum().sort_values(ascending=False)

StartMonth
8     1.156203e+09
7     1.101848e+09
6     7.910910e+08
5     7.710183e+08
9     7.021504e+08
1     6.912760e+08
4     6.256263e+08
3     6.175581e+08
2     6.020396e+08
12    4.136980e+08
11    3.071256e+08
10    2.551886e+08
Name: DemandPerMonth, dtype: float64

In [10]:
df.groupby('StartMonth')['Demand'].sum().sort_values(ascending=False)

StartMonth
8     143041.27
7     139686.65
6     117564.42
5     115283.83
9     111771.80
1     109639.33
4     104253.67
3     103896.05
2     103141.96
12     85158.09
11     71741.55
10     64933.48
Name: Demand, dtype: float64

In [11]:
df.columns

Index(['UserID', 'ChargerID', 'ChargerCompany', 'Location', 'ChargerType',
       'StartDay', 'StartTime', 'EndDay', 'EndTime', 'StartDatetime',
       'EndDatetime', 'Duration', 'Demand', 'StartMonth', 'StartWeek',
       'EndMonth', 'EndWeek', 'DemandPerMonth'],
      dtype='str')

In [12]:
df['StartDayOfWeek'] = pd.to_datetime(df['StartDay']).dt.day_name()

In [13]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek
28158,0,208,1,golf,0,2022-04-24,12:06:43,2022-04-24,13:18:17,2022-04-24 12:06:00,2022-04-24 13:18:00,68,6.50,4,6,4,6,104253.67,Sunday
26276,0,185,1,golf,0,2022-07-23,15:26:28,2022-07-23,17:15:31,2022-07-23 15:26:00,2022-07-23 17:15:00,109,6.67,7,5,7,5,139686.65,Saturday
63013,917,1202,0,public institution,0,2022-07-27,19:20:35,2022-07-27,20:02:47,2022-07-27 19:20:00,2022-07-27 20:02:00,42,2.70,7,2,7,2,139686.65,Wednesday

In [14]:
df['DemandPerDay'] = df.groupby('StartDayOfWeek')['Demand'].transform('mean').round(2)

In [15]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay
20053,0,123,1,apartment,0,2022-08-21,20:43:56,2022-08-21,23:20:18,2022-08-21 20:43:00,2022-08-21 23:20:00,156,16.80,8,6,8,6,143041.27,Sunday,17.81
35174,63,286,0,hotel,0,2022-03-19,17:32:04,2022-03-19,21:37:58,2022-03-19 17:32:00,2022-03-19 21:37:00,246,20.00,3,5,3,5,103896.05,Saturday,17.41
538,0,3,1,company,0,2022-05-25,13:14:38,2022-05-25,14:48:04,2022-05-25 13:14:00,2022-05-25 14:48:00,93,9.84,5,2,5,2,115283.83,Wednesday,17.53

In [16]:
df.groupby('StartDayOfWeek')['DemandPerDay'].mean()

StartDayOfWeek
Friday       17.31
Monday       17.35
Saturday     17.41
Sunday       17.81
Thursday     17.62
Tuesday      17.10
Wednesday    17.53
Name: DemandPerDay, dtype: float64

In [17]:
df.groupby('StartDayOfWeek')['DemandPerDay'].sum().round(2).sort_values(ascending=False)

StartDayOfWeek
Thursday     194701.00
Wednesday    190691.34
Friday       190548.48
Tuesday      182012.40
Monday       179069.35
Saturday     173037.99
Sunday       160040.66
Name: DemandPerDay, dtype: float64

In [18]:
df.shape

(72826, 20)

In [19]:
df.sample(2)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay
15604,0,88,1,apartment,0,2022-05-23,17:57:47,2022-05-23,20:42:21,2022-05-23 17:57:00,2022-05-23 20:42:00,165,18.20,5,0,5,0,115283.83,Monday,17.35
67073,184,1525,0,public area,1,2022-08-16,16:51:25,2022-08-16,17:10:57,2022-08-16 16:51:00,2022-08-16 17:10:00,20,12.61,8,1,8,1,143041.27,Tuesday,17.10

In [20]:
df_ = pd.read_csv(dataset_path)
df_.shape

(72826, 14)

In [21]:
print(f'before feature engineering, shape of the dataset is {df_.shape}')

print(f'after appling feature engineering, shape of the dataset i s{df.shape}')

before feature engineering, shape of the dataset is (72826, 14)
after appling feature engineering, shape of the dataset i s(72826, 20)

In [22]:
feature_dir = p_dir.FEATURED_DIR

In [27]:
from datetime import time

df['StartTime'] = pd.to_datetime(df['StartTime'],format='%H:%M:%S').dt.time

df['Shift'] = df['StartTime'].apply(
    lambda x: 'Day' if x < time(14,0) else 'Night'
)

In [29]:
df.groupby('Shift')['Demand'].mean().round(2)

Shift
Day      15.50
Night    18.67
Name: Demand, dtype: float64

In [35]:
df.groupby('Shift')['Demand'].count()

Shift
Day      28259
Night    44567
Name: Demand, dtype: int64

In [36]:
df.to_csv(feature_dir/'featured_dataset.csv')

In [24]:
df.sample(3)

,UserID,ChargerID,ChargerCompany,Location,ChargerType,StartDay,StartTime,EndDay,EndTime,StartDatetime,EndDatetime,Duration,Demand,StartMonth,StartWeek,EndMonth,EndWeek,DemandPerMonth,StartDayOfWeek,DemandPerDay
40927,1124,372,1,apartment,0,2022-07-02,20:21:28,2022-07-02,23:56:45,2022-07-02 20:21:00,2022-07-02 23:56:00,215,23.32,7,5,7,5,139686.65,Saturday,17.41
9731,0,43,1,resort,0,2022-08-07,11:42:27,2022-08-07,13:12:35,2022-08-07 11:42:00,2022-08-07 13:12:00,90,8.90,8,6,8,6,143041.27,Sunday,17.81
21009,0,130,1,golf,0,2022-09-28,18:47:32,2022-09-28,18:51:03,2022-09-28 18:47:00,2022-09-28 18:51:00,4,0.40,9,2,9,2,111771.80,Wednesday,17.53